services:

  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: asr-api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/models
    environment:
      - ASR_QE_MODEL_PATH=/models/v20251212_154204/model.joblib
      - LOG_LEVEL=INFO
    networks:
      - asr-network

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: asr-prometheus
    ports:
      - "9191:9090"
    volumes:
      - ./conf/monitoring/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./conf/monitoring/alerts.yml:/etc/prometheus/alerts.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - asr-network
    depends_on:
      - api

  grafana:
    image: grafana/grafana:10.0.0
    container_name: asr-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./conf/monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./conf/monitoring/grafana/dashboards:/etc/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - asr-network
    depends_on:
      - prometheus

  spark-master:
    build:
      context: .
      dockerfile: docker/spark/Dockerfile
    container_name: spark-master
    command: >
      /bin/bash -c " /app/.venv/bin/spark-class org.apache.spark.deploy.master.Master --host spark-master --port 7077 --webui-port 8080 "
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./data:/opt/data
      - ./jobs:/app/jobs
      - ./src:/app/src
    networks:
      - asr-network

  spark-worker:
    build:
      context: .
      dockerfile: docker/spark/Dockerfile
    container_name: spark-worker
    command: >
      /bin/bash -c " /app/.venv/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077 "
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
    depends_on:
      - spark-master
    volumes:
      - ./data:/opt/data
    networks:
      - asr-network

  # AIRFLOW SERVICES
  postgres:
    image: postgres:13
    container_name: airflow-postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    networks:
      - asr-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-init:
    build:
      context: .
      dockerfile: docker/airflow/Dockerfile
    container_name: airflow-init
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=false
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
    depends_on:
      - postgres
    networks:
      - asr-network
    command: >
      bash -c "airflow db migrate && airflow users create --username admin --password admin --firstname Jesse --lastname Wonnink --role Admin --email admin@example.com"

  airflow-webserver:
    build:
      context: .
      dockerfile: docker/airflow/Dockerfile
    container_name: airflow-webserver
    restart: always
    command: webserver
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      postgres:
        condition: service_started
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=false
      - AIRFLOW__CONN__SPARK_DEFAULT=spark://spark-master:7077
    ports:
      - "8081:8080" # Avoid conflict with Spark 8080
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/data
      - ./src:/opt/airflow/src
      - ./models:/models
      - ./conf:/opt/airflow/conf
      - ./jobs:/opt/airflow/jobs
    networks:
      - asr-network

  airflow-scheduler:
    build:
      context: .
      dockerfile: docker/airflow/Dockerfile
    container_name: airflow-scheduler
    restart: always
    command: scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      postgres:
        condition: service_started
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=false
      - AIRFLOW__CONN__SPARK_DEFAULT=spark://spark-master:7077
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/data
      - ./src:/opt/airflow/src
      - ./models:/models
      - ./conf:/opt/airflow/conf
      - ./jobs:/opt/airflow/jobs
    networks:
      - asr-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  asr-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  postgres_data:
